# Generated by Django 4.2.9 on 2024-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='Region',
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='Topics',
            field=models.CharField(default='none', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
