# Generated by Django 4.2.2 on 2024-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(blank=True, default=None, max_length=255, null=True)),
                ('intensity', models.CharField(default=None, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('insight', models.CharField(default=None, max_length=255, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_year', models.IntegerField(default=None, max_length=255, null=True)),
                ('impact', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('added', models.CharField(default=None, max_length=255, null=True)),
                ('published', models.CharField(default=None, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('relevance', models.CharField(default=None, max_length=255, null=True)),
                ('pestle', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('source', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('likelihood', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
