# Generated by Django 4.2.9 on 2024-01-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_dataentry_region_alter_dataentry_topics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Likelihood',
            new_name='likelihood',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Relevance',
            new_name='relevance',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Topics',
            new_name='topics',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Year',
            new_name='year',
        ),
    ]
